config/routes.rb
Rails.application.routes.draw do

  match "/index" => "aqua#index", via: :get
  match "/events" => "aqua#events", via: :get
  match "/shop" => "aqua#shop", via: :get
  match "/discussion" => "aqua#discussion", via: :get
  

  root 'aqua#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/aqua_controller.rb
class AquaController < ApplicationController
  def index
  	@title = "Main Index Page"
  end

  def events
  	@title = "Events"
  end

  def shop
  	@title = "Shop"
  end

  def discussion
  	@title = "Discussion"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#Return a title on a per-page basis

	def title 
		base_title = "Jahangir & Co."
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
			
		end
	end
	
end

app/helpers/aqua_helper.rb
module AquaHelper
	
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/aqua/discussion.html.erb
<h1>Aqua#discussion</h1>
<p>Find me in app/views/aqua/discussion.html.erb</p>

app/views/aqua/events.html.erb
<h1>Aqua#events</h1>
<p>Find me in app/views/aqua/events.html.erb</p>

app/views/aqua/index.html.erb
<h1>Aqua#index</h1>
<p>Find me in app/views/aqua/index.html.erb</p>

app/views/aqua/shop.html.erb
<h1>Aqua#shop</h1>
<p>Find me in app/views/aqua/shop.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
	<footer>

 © <%= Time.now.year %> Jahangir & Co.

</footer>
</footer>

app/views/layouts/_header.html.erb
<header>
<h1> I am Header </h1>
<h4> Contains all information related to header </h4> 
</header>

app/views/layouts/_navigation.html.erb
<nav>

 <ul>

	 <li><%= link_to "Home", root_path %></li>

	 <li><%= link_to "Events", events_path %></li>

	 <li><%= link_to "Discussion", discussion_path %></li>

	 <li><%= link_to "Shop", shop_path %></li>

	 <li> The main thing is : <%= shop_path puts "Welcome"%></li>

 </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/navigation' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>